/**
 * Directory data for series pages.
 *
 * Series are real content files rather than pages generated by pagination. Two
 * reasons: it gives the artist somewhere to write about a body of work, and it
 * sidesteps an Eleventy constraint — with dynamic permalinks disabled (they must
 * be, because rendering a permalink through WebC invokes its CSS bundler before
 * `page` exists), a paginated template's permalink function is never evaluated.
 * A file-backed page has its permalink computed in time.
 */

interface SeriesContext {
  readonly page: { readonly fileSlug: string }
}

export default {
  layout: 'series.webc',
  tags: 'series',
  eleventyComputed: {
    permalink: ({ page }: SeriesContext): string => `/series/${page.fileSlug}/`,
  },
}
